### ISSUE TITLE
Feature request: Allow currency symbols in math operations

### ISSUE THREAD

**Issue by defrex** [heyman/heynote#230]
**Have you searched existing Github issues to see if someone has already requested this feature?**
Yes

**Is your feature request related to a problem? Please describe.**
I often need to do math on dollar values, and copy/paste them in with `$`s. Unfortunately the currency symbols prevent the math from working, forcing me to manually strip them out before I can see the results.

**Describe the solution you'd like**
Just ignore the currency symbols and perform the math operations on the number.

**Comment by heyman** [comment]
Heynote uses Math.js for Math blocks. Dollar signs in the Math.js syntax has [been discussed in their repo](https://github.com/josdejong/mathjs/issues/895) and it seems that some people want to be able to use `$` in variable names, while others want it to denote USD currency like you. 

I'm not too keen on diverging too much from Math.js syntax, and since there are ambiguous use cases for the dollar sign, I don't want to change this behaviour at the moment.
