### ISSUE TITLE
Leverage Tauri, this app does not need to be 180mb

### ISSUE THREAD

**Issue by fayazara** [heyman/heynote#237]
**Disclaimer**
This is not an "Issue/Feature request", discussions are not enabled. Just wanted to have a "Discussion" on this.

This app is around 180mb which I feel is not necessary, I've built a few apps with tauri and it works perfectly well with monaco editor and the app size is almost native size (20-30 mb).

**Comment by heyman** [comment]
I considered Tauri, but decided to go with Electron. Knowing exactly which browser engine and version will run the program outweighed the saved disk space (especially since I want Heynote to work on multiple operating systems and versions). The project maturity of Electron, and the fact that it gave Heynote automatic updates with very little effort, is an added bonus.

**Comment by dy228a** [comment]
On my computer, Heynote was slow to start, which I thought was a drawback of Electron and Snap. I had OpenCode refactor Heynote to use Tauri, and after several attempts and debugging, it worked! The generated executable was only 13MB, and it started up incredibly fast. Now I no longer worry about the startup time of Heynote on my computer.
