### ISSUE TITLE
Feature request: Autocomplete for code

### ISSUE THREAD

**Issue by Explosion-Scratch** [heyman/heynote#28]
I think the monaco editor suppoorts this:

<img width="495" alt="image" src="https://github.com/heyman/heynote/assets/61319150/facbf4fe-0d32-46e7-b780-8d907fba9788">

I'll send a PR if I get a chance 😀

**Comment by heyman** [comment]
`CodeMirror` does have some support for auto complete. However, I've turned it off because it wasn't working very well. I've decided to not suport auto complete (at least for now) to keep complexity down. I think the use case for writing a lot of code within Heynote should be small (you probably have an IDE for that).

**Comment by Explosion-Scratch** [comment]
> `CodeMirror` does have some support for auto complete. However, I've turned it off because it wasn't working very well. I've decided to not suport auto complete (at least for now) to keep complexity down. I think the use case for writing a lot of code within Heynote should be small (you probably have an IDE for that).

I find it very helpful even for snippets, it doesn't have to be anything custom, or have snippets support but the intellisense is super helpful for figuring out if things aren't defined, hovering over functions, etc
