### ISSUE TITLE
Feature Request: support multiple files

### ISSUE THREAD

**Issue by edwinbernadus** [heyman/heynote#65]
Do you support multiple files in the future?

Is it possible to have the menu open and save the file?
what is the philosophy of the app? 
do you want to keep only use one buffer text file?

btw, i love the app
I use it daily

**Comment by zlykh** [comment]
+1
It would be great to have tabs, like Sublime or NPP do.

**Comment by brpaz** [comment]
Just discovered Heynote. I really like the idea.  Expanding a bit to the multiple files support. I think it could be interesting to have like one file per day. (sort like a dev diary), that could be archived after X time.

**Comment by heyman** [comment]
At the moment, I'm not planning to add support for saving/loading files. I believe adding that is a slippery slope towards becoming a fully-fledged editor, which I think would make Heynote worse for the original use-case due to loss of simplicity/focus.

I haven't fully decided whether to support more than one buffer, though.

**Comment by heyman** [comment]
Closing as wontfix. Exporting blocks to files can be tracked in #9
