### ISSUE TITLE
How do you render Markdown?

### ISSUE THREAD

**Issue by eiannimaersk** [heyman/heynote#87]
Hi,
love heynote! I'm trying to understand what I'm doing wrong but basically, when I see your example in markdown I see this:

<img width="539" alt="Screenshot 2023-12-28 at 08 37 17" src="https://github.com/heyman/heynote/assets/95409111/a313f70c-37ee-4520-a683-f4b31000eec1">

But when I try I don't see markdown rendered although the block is in markdown:

<img width="173" alt="Screenshot 2023-12-28 at 08 37 45" src="https://github.com/heyman/heynote/assets/95409111/e82cd619-31af-47c2-804a-73d1d4afb6a6">

It doesn't show the header as actual header.

What am I doing wrong?

**Comment by heyman** [comment]
That's expected. The Markdown mode just provides syntax highlighting, and it's not supposed to show rendered Markdown.

**Comment by robertripoll** [comment]
> That's expected. The Markdown mode just provides syntax highlighting, and it's not supposed to show rendered Markdown.

Is the possibility of rendering Markdown in the roadmap?

**Comment by heyman** [comment]
No, most likely not.

**Comment by ManBearPigg** [comment]
Markdown syntax highlighting is an unusual concept and its merits are suspicious tbh.

So why are we able to render some Markdown elements but not others? Probably because they are both useful, and in the spirit of HeyNote. The checklist, for example, is perfect here. The Markdown code editor 

I'll suggest that there are other Markdown elements that a user would like to render without opening a separate Markdown editor. 

- Headings
- Bold
- Italic
- Horizontal Rule
- Link

This is just basic note structuring that has existed for decades.  Yeah Markdown editors already exist. But so do code editors. So do calculators. Anyways it's your slippery slope to be the judge of.

Great app, ty.
